### ISSUE TITLE
usersがないとSQLのエラーが出ている

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nako3storage#198]
```
  thrown in /n3s.nadesi.com/app/fw_simple/fw_database.lib.php on line 85
[15-Aug-2024 09:09:50 Asia/Tokyo] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: users in /n3s.nadesi.com/app/fw_simple/fw_database.lib.php:85
Stack trace:
#0 /n3s.nadesi.com/app/fw_simple/fw_database.lib.php(85): PDO->prepare('UPDATE users se...')
#1 /n3s.nadesi.com/app/action/userinfo.inc.php(41): db_exec('UPDATE users se...', Array)
#2 /n3s.nadesi.com/app/index.inc.php(41): n3s_web_userinfo()
#3 /n3s.nadesi.com/app/index.inc.php(18): n3s_action()
#4 /n3s.nadesi.com/app/index.inc.php(12): n3s_main()
#5 /n3s.nadesi.com/index.php(17): include_once('/home/users/1/k...')
#6 {main}
  thrown in /n3s.nadesi.com/app/fw_simple/fw_database.lib.php on line 85
```

**Comment by kujirahand** [comment]
ユーザーのプロフィール更新でエラーが出ていました。
